-- Idempotent schema update for Postgres.
-- Apply with: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/db_update.sql

BEGIN;

-- USERS
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR NULL,
  username VARCHAR NULL,
  password_hash VARCHAR NOT NULL,
  name VARCHAR NOT NULL DEFAULT 'User',
  gender VARCHAR NOT NULL,
  country VARCHAR NOT NULL,
  description TEXT NULL,
  image_url VARCHAR NULL,
  is_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

-- Backfill/ensure columns exist (safe for older schemas)
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS country VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS image_url VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_subscribed BOOLEAN;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_video_total_count INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS free_video_opposite_count INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;

-- Apply defaults where missing
ALTER TABLE users ALTER COLUMN name SET DEFAULT 'User';
ALTER TABLE users ALTER COLUMN is_subscribed SET DEFAULT FALSE;
ALTER TABLE users ALTER COLUMN free_video_total_count SET DEFAULT 0;
ALTER TABLE users ALTER COLUMN free_video_opposite_count SET DEFAULT 0;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT NOW();

-- Backfill counters if NULL (older rows)
UPDATE users SET free_video_total_count = 0 WHERE free_video_total_count IS NULL;
UPDATE users SET free_video_opposite_count = 0 WHERE free_video_opposite_count IS NULL;

-- Uniqueness + lookup indexes
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email_unique ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username_unique ON users (username);

-- CHAT SESSIONS
CREATE TABLE IF NOT EXISTS chat_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mode VARCHAR NOT NULL,
  user_a_id INTEGER NOT NULL,
  user_b_id INTEGER NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS mode VARCHAR;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS user_a_id INTEGER;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS user_b_id INTEGER;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE chat_sessions ALTER COLUMN created_at SET DEFAULT NOW();

CREATE INDEX IF NOT EXISTS ix_chat_sessions_user_a_id ON chat_sessions (user_a_id);
CREATE INDEX IF NOT EXISTS ix_chat_sessions_user_b_id ON chat_sessions (user_b_id);
CREATE INDEX IF NOT EXISTS ix_chat_sessions_created_at ON chat_sessions (created_at);

DO $$
BEGIN
  ALTER TABLE chat_sessions
    ADD CONSTRAINT chat_sessions_user_a_id_fkey
    FOREIGN KEY (user_a_id) REFERENCES users (id);
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE chat_sessions
    ADD CONSTRAINT chat_sessions_user_b_id_fkey
    FOREIGN KEY (user_b_id) REFERENCES users (id);
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- CHAT MESSAGES
CREATE TABLE IF NOT EXISTS chat_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  sender_id INTEGER NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS session_id INTEGER;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS sender_id INTEGER;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS message TEXT;
ALTER TABLE chat_messages ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE chat_messages ALTER COLUMN created_at SET DEFAULT NOW();

CREATE INDEX IF NOT EXISTS ix_chat_messages_session_id ON chat_messages (session_id);
CREATE INDEX IF NOT EXISTS ix_chat_messages_created_at ON chat_messages (created_at);

DO $$
BEGIN
  ALTER TABLE chat_messages
    ADD CONSTRAINT chat_messages_session_id_fkey
    FOREIGN KEY (session_id) REFERENCES chat_sessions (id);
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE chat_messages
    ADD CONSTRAINT chat_messages_sender_id_fkey
    FOREIGN KEY (sender_id) REFERENCES users (id);
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

-- SWIPES
CREATE TABLE IF NOT EXISTS swipes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  target_user_id INTEGER NOT NULL,
  direction VARCHAR NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE swipes ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE swipes ADD COLUMN IF NOT EXISTS target_user_id INTEGER;
ALTER TABLE swipes ADD COLUMN IF NOT EXISTS direction VARCHAR;
ALTER TABLE swipes ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE swipes ALTER COLUMN created_at SET DEFAULT NOW();

CREATE INDEX IF NOT EXISTS ix_swipes_user_id ON swipes (user_id);
CREATE INDEX IF NOT EXISTS ix_swipes_target_user_id ON swipes (target_user_id);
CREATE INDEX IF NOT EXISTS ix_swipes_created_at ON swipes (created_at);

DO $$
BEGIN
  ALTER TABLE swipes
    ADD CONSTRAINT swipes_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id);
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE swipes
    ADD CONSTRAINT swipes_target_user_id_fkey
    FOREIGN KEY (target_user_id) REFERENCES users (id);
EXCEPTION WHEN duplicate_object THEN
  NULL;
END $$;

COMMIT;
